server:
  port: 2500

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/poplar?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8

mybatis:
  # 搜索指定包别名
  type-aliases-package: com.phoenix..dao.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations:  classpath:mapper/*Mapper.xml